import type { Metadata } from "next";
import { PageShell } from "../components/page-shell";

export const metadata: Metadata = {
  title: "About · LA Budget Explorer",
  description:
    "Learn how LA Budget Explorer helps Angelenos understand how the city spends public funds.",
};

const STEPS = [
  {
    step: "01",
    title: "Ask a question",
    description:
      "Type any question about the LA city budget in plain language — no jargon or document navigation required.",
  },
  {
    step: "02",
    title: "AI searches official documents",
    description:
      "Our system retrieves relevant passages from adopted budgets, CAO reports, and departmental summaries.",
  },
  {
    step: "03",
    title: "Get a sourced answer",
    description:
      "Receive a clear response with citations back to the original budget documents so you can verify every claim.",
  },
];

export default function AboutPage() {
  return (
    <PageShell>
      <main className="relative z-10 mx-auto w-full max-w-3xl flex-1 px-6 py-16 md:py-24">
        <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-white/50 bg-white/35 px-4 py-1.5 text-xs uppercase tracking-[0.15em] text-[rgba(60,30,80,0.75)] backdrop-blur-sm">
          <span className="size-1.5 rounded-full bg-[#c97ab0]" />
          Civic transparency
        </div>

        <h1 className="mb-6 font-serif text-[clamp(2.2rem,5vw,3.5rem)] leading-[1.1] font-semibold tracking-[-0.02em] text-[#2d1240]">
          About <span className="italic text-[#a0497a]">This Project</span>
        </h1>

        <p className="mb-12 max-w-2xl text-lg leading-[1.7] font-light text-[rgba(60,30,80,0.6)]">
          LA Budget Explorer makes the city&apos;s $13+ billion budget accessible
          to everyone. Public money should be easy to understand — not buried in
          hundreds of pages of PDFs.
        </p>

        <div className="mb-12 space-y-6">
          {STEPS.map((item) => (
            <div
              key={item.step}
              className="flex gap-5 rounded-2xl border border-white/65 bg-white/45 p-6 shadow-[0_8px_40px_rgba(100,40,120,0.08),inset_0_1px_0_rgba(255,255,255,0.7)] backdrop-blur-xl"
            >
              <span className="font-serif text-2xl font-semibold text-[#a0497a]">
                {item.step}
              </span>
              <div>
                <h2 className="mb-2 text-lg font-medium text-[#2d1240]">
                  {item.title}
                </h2>
                <p className="text-sm leading-relaxed font-light text-[rgba(60,30,80,0.6)]">
                  {item.description}
                </p>
              </div>
            </div>
          ))}
        </div>

        <div className="rounded-2xl border border-white/65 bg-white/45 p-6 shadow-[0_8px_40px_rgba(100,40,120,0.08),inset_0_1px_0_rgba(255,255,255,0.7)] backdrop-blur-xl">
          <h2 className="mb-3 text-lg font-medium text-[#2d1240]">
            A note on accuracy
          </h2>
          <p className="text-sm leading-relaxed font-light text-[rgba(60,30,80,0.6)]">
            Answers are generated by AI from official city documents and may
            occasionally contain errors. Always check the cited sources for
            important decisions. This tool is for informational purposes and is
            not affiliated with the City of Los Angeles.
          </p>
        </div>
      </main>
    </PageShell>
  );
}
